version: '3'
services:
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    #ports:
     # - "2181:2181"
    expose:
      - "2181"  
    networks:
      - kafka-net
    environment:
      JVMFLAGS: -Djava.security.auth.login.config=/etc/kafka/zookeeper_jaas.conf

    volumes:
      - ./zookeeper_jaas.conf:/etc/kafka/zookeeper_jaas.conf
      - ./zookeeper-data:/data
      - ./zookeeper-logs:/datalog
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    user: "1000:1000"
    
    ports:
      - "9092:9092"
      - "9093:9093"
    
    environment:
      
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
   
      #KAFKA_OPTS: -Djavax.net.ssl.keyStore=/etc/kafka/broker.ks -Djavax.net.ssl.keyStorePassword=V4Paseipif -Djavax.net.ssl.trustStore=/etc/kafka/broker.ts -Djavax.net.ssl.trustStorePassword=V4Paseipif -Djavax.net.debug=ssl -Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf
      
      
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://85.239.238.109:9093
      KAFKA_LISTENER_NAME_OUTSIDE: OUTSIDE
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/my_kafka_broker.ks
      KAFKA_SSL_KEYSTORE_PASSWORD: MySecretPasswordToBeReplaced
      KAFKA_SSL_KEY_PASSWORD: MySecretPasswordToBeReplaced
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/my_kafka_broker.ts
      KAFKA_SSL_TRUSTSTORE_PASSWORD: MySecretPasswordToBeReplaced
      KAFKA_LOG4J_LOGGER_KAFKA: DEBUG
      KAFKA_SSL_CLIENT_AUTH: "none"
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""      
      

    
    command: ["sh", "/etc/kafka/generate_keys.sh"]

    volumes:
      - ./generate_keys.sh:/etc/kafka/generate_keys.sh
      - ./my_kafka_broker.ks:/etc/kafka/my_kafka_broker.ks
      - ./my_kafka_broker.ts:/etc/kafka/my_kafka_broker.ts
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
      #- ./kafka-data/data:/var/lib/kafka/data
   
    depends_on:
      - zookeeper
    networks:
      - kafka-net
networks:
  kafka-net:
    driver: bridge


